### ISSUE TITLE
Axios error when starting in Angular project

### ISSUE THREAD

**Issue by vinicamposdev** [DevCycleHQ/js-sdks#467]
I'm having a particular problem with a angular legacy project, in angular 1.5.x and node lts/fermium (14.20.22). I'm trying to initialize the with my credentials. In node SDK works, but in js SDK get this strange error on axios.

This occurs when I import the initialize:
import { initialize } from '@devcycle/devcycle-js-sdk'

<img width="424" alt="image" src="https://user-images.githubusercontent.com/68520055/228962069-d3db8dce-7b17-4aeb-a072-ac0607f0cabc.png">

**Comment by vinicamposdev** [comment]
Yeah, sure.
```bash
Uncaught TypeError: axios_1.default.create is not a function
    at eval (Request.js?96f2:10:1)
    at Object.lvLo (agency-c02f4500c1872af53939.js:19430:1)
    at __webpack_require__ (agency-c02f4500c1872af53939.js:90:30)
    at eval (EventQueue.js?59c4:4:1)
    at Object.WcSb (agency-c02f4500c1872af53939.js:13173:1)
    at __webpack_require__ (agency-c02f4500c1872af53939.js:90:30)
    at eval (RequestEvent.js?8e1e:5:1)
    at Object.jh4R (agency-c02f4500c1872af53939.js:18501:1)
    at __webpack_require__ (agency-c02f4500c1872af53939.js:90:30)
    at eval (utils.js?cfd5:4:1)
    at z9X+ (agency-c02f4500c1872af53939.js:24650:1)
    at __webpack_require__ (agency-c02f4500c1872af53939.js:90:30)
    at eval (Variable.js?39c0:4:1)
    at Object.OcDv (agency-c02f4500c1872af53939.js:10200:1)
    at __webpack_require__ (agency-c02f4500c1872af53939.js:90:30)
    at eval (Client.js?aafc:7:1)
    at Object.qvz3 (agency-c02f4500c1872af53939.js:21339:1)
    at __webpack_require__ (agency-c02f4500c1872af53939.js:90:30)
    at eval (index.js?880a:18:1)
    at Object.iApE (agency-c02f4500c1872af53939.js:17848:1)
    at __webpack_require__ (agency-c02f4500c1872af53939.js:90:30)
    at eval (feature-flag-provider.js?8664:1:1)
    at Module.hmQR (agency-c02f4500c1872af53939.js:17587:1)
    at __webpack_require__ (agency-c02f4500c1872af53939.js:90:30)
    at eval (app_init.js?8f61:1:1)
    at Module.j2F0 (agency-c02f4500c1872af53939.js:18275:1)
    at __webpack_require__ (agency-c02f4500c1872af53939.js:90:30)
    at eval (index.js?a876:1:1)
    at Module.qHa2 (agency-c02f4500c1872af53939.js:21092:1)
    at __webpack_require__ (agency-c02f4500c1872af53939.js:90:30)
    at eval (index.js?5351:1:1)
    at Module.U1EC (agency-c02f4500c1872af53939.js:12217:1)
    at __webpack_require__ (agency-c02f4500c1872af53939.js:90:30)
    at eval (index.js?2b87:1:1)
    at Module.K4dG (agency-c02f4500c1872af53939.js:8579:1)
    at __webpack_require__ (agency-c02f4500c1872af53939.js:90:30)
    at eval (app.js?f538:1:1)
    at 9TjT (agency-c02f4500c1872af53939.js:4566:1)
    at __webpack_require__ (agency-c02f4500c1872af53939.js:90:30)
    at 4 (agency-c02f4500c1872af53939.js:2657:18)
    at __webpack_require__ (agency-c02f4500c1872af53939.js:90:30)
    at checkDeferredModules (agency-c02f4500c1872af53939.js:46:23)
    at agency-c02f4500c1872af53939.js:268:18
    at agency-c02f4500c1872af53939.js:271:10
    
  ```

**Comment by nikolasleblanc** [comment]
Are you able to provide a minimum repo?

**Comment by vinicamposdev** [comment]
I manage to skip this error installing the cdn

But I came into other one
 ```js
  const user = {
    userid: '102...',
    name: 'Vinicius Campos',
    // customData: {
    //   customKey: 'customValue'
    // }
  }
  const dvcOptions = { logLevel: 'debug' }
  try {
    const dvcClient = DevCycle.initialize('dvc_client_7...', user, dvcOptions)
    const variable = dvcClient.variable(user, 'DEMO-FEATURE-FLAG', true)
 ```
 
 That throws an error like:
 ```bash
 Error: key is not of type string — utils.ts:45
 ```

**Comment by vinicamposdev** [comment]
Turns out that the user was verifying as a string, so I just duplicated the SDK key and works just fine
